version: '3.9'

services:
  middleware:
    container_name: middleware
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/usr/src/middleware
      - ~/logs:/usr/src/middleware/logs
    env_file:
      - ".env"

    labels:
      - "traefik.enable=true"

      # HTTP router with redirection to HTTPS
      - "traefik.http.routers.middleware-http.rule=Host(`aonet-api4me.devop4me.com`) && PathPrefix(`/ajustar-dados`)"
      - "traefik.http.routers.middleware-http.entrypoints=http"
      - "traefik.http.routers.middleware-http.middlewares=redirect-to-https"

      # Middleware for redirecting to HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # HTTPS router with TLS
      - "traefik.http.routers.middleware-https.rule=Host(`aonet-api4me.devop4me.com`) && PathPrefix(`/ajustar-dados`)"
      - "traefik.http.routers.middleware-https.entrypoints=https"
      - "traefik.http.routers.middleware-https.tls.certresolver=myresolver"

      # delete for prod?
      # router for localhost http
      # - "traefik.http.routers.middleware-localhost-http.rule=Host(`localhost`) && PathPrefix(`/ajustar-dados`)"
      # - "traefik.http.routers.middleware-localhost-http.entrypoints=http"
      # - "traefik.http.routers.middleware-localhost-http.middlewares=redirect-to-https"
      # # HTTPS router for localhost
      # - "traefik.http.routers.middleware-localhost-https.rule=Host(`localhost`) && PathPrefix(`/ajustar-dados`)"
      # - "traefik.http.routers.middleware-localhost-https.entrypoints=https"
      # - "traefik.http.routers.middleware-localhost-https.tls.certresolver=myresolver"

      # Service configuration
      - "traefik.http.services.middleware-http.loadbalancer.server.port=3000"
    networks:
      - net-middleware

  traefik:
    container_name: traefik
    image: traefik:v2.5
    restart: always
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--log.level=DEBUG"
      - "--log.filePath=/var/log/traefik.log"
      - "--accesslog.filePath=/var/log/access.log"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.myresolver.acme.email=seu-email@exemplo.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./logs:/var/log
      - ./letsencrypt:/letsencrypt
    networks:
      - net-middleware

networks:
  net-middleware:
    driver: bridge